### ISSUE TITLE
Mock client sends invalid JSON POST request to ambi backend for sensor readings

### ISSUE THREAD

**Issue by wumbabum** [Jim-Hodapp-Coaching/ambi_mock_client#1]
Ambi backend interprets JSON [here](https://github.com/Jim-Hodapp-Coaching/ambi_client_cpp/blob/7aac57aa8a82d1a29085f185eed6b34582322c79/src/sensorchi.ino#L165)

Currently, the mock client sends an invalid JSON request, which ambi receives and is unable to parse.
This results in an empty parameters field on the backend.

See [this issue](https://github.com/Jim-Hodapp-Coaching/ambi/issues/6) for an example of the ambi response

**Comment by bortyr** [comment]
This is what I got from tcpdump and displaying it in wireshark
![image](https://user-images.githubusercontent.com/62113056/152696815-bc8eff56-d855-4f3a-8661-d6dbc506c119.png)

**Comment by jhodapp** [comment]
One note, temperature is spelled "tempurature" which is not correct.

**Comment by jhodapp** [comment]
Ah I think I know what the issue is, Wireshark doesn't see the JSON as JSON, nor will the Phoenix server because we're not passing the content-type in the HTTP header like I do in the full hardware client, e.g.: https://github.com/Jim-Hodapp-Coaching/ambi_client_cpp/blob/7aac57aa8a82d1a29085f185eed6b34582322c79/src/http_client.cpp#L132

@bortyr

**Comment by bortyr** [comment]
Yes, that's what I thought. I saw an example on stackoverflow (can't link it because SO is offline for maintenance) where somebody suggested using .json() method and sets the header accordingly to this. Though when I tried to do it quickly, lsp told me that .json method doesn't exist so maybe I missed something and simply setting .header(json/application (or sth like that)) should suffice
